#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require_relative 'lib/interpreter'

options = ARGV.getopts('', 'verbose', symbolize_names: true)
path = ARGV[0]
Interpreter.new(path, options).execute
